### ISSUE TITLE
Code review for coding style.

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#1]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/d5aed810e1aee9966a144a0cfc16ff3720b87b63/ex10.py#L20

remove the dead code, do not include the dead code anywhere

**Comment by jilesingh** [comment]
New changes have been made to the code. Could you please review and give me feedback.

Thanks and regards
Jile Singh

**Comment by ABresting** [comment]
looks good, thanks
