### ISSUE TITLE
Code review, code comments multiline

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#2]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/d5aed810e1aee9966a144a0cfc16ff3720b87b63/ex10.py#L26

in the first line do not include any comment just write the ''' or """ and then include from the next line
for eg.
"""
<comment>
"""

**Comment by jilesingh** [comment]
its has been corrected

**Comment by jilesingh** [comment]
New changes have been made. Could you please review and give me feedback.
Thanks and regards
Jile Singh

**Comment by ABresting** [comment]
looks fine, thanks
