### ISSUE TITLE
Remove test file.

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#3]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/d95b6b7e8d3807572c5e2213b201b6f73a00647b/chapter1/new_file.txt#L1

Remove this test file, it's of no use.

**Comment by jilesingh** [comment]
Test file is removed. Thanks for the feedback.

**Comment by ABresting** [comment]
its not removed yet, I can still see "new_file.txt" in chapter 1

**Comment by jilesingh** [comment]
Sorry. I thought I supposed to remove only test file. It's removed now. could you please check it again ?

**Comment by ABresting** [comment]
looks good.
