### ISSUE TITLE
Loop condition variable 

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#6]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/2a5a728acc6485f8902871c15343c1e6b75cbaef/chapter1/ex33.py#L7

Why only 6 times? Also, if you are hardcoding something then, try using it as a variable. You can use loopCount = 6 and then use the variable loopCount in the while condition

**Comment by jilesingh** [comment]
Some new changes have been made in code. I have used a variable. can you please check and notify me. 
Thanks

**Comment by ABresting** [comment]
good.
