### ISSUE TITLE
use uniform comment body

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#8]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/2a5a728acc6485f8902871c15343c1e6b75cbaef/chapter1/ex31.py#L39

in previous code files you have used a different comment message and here you are using different, it should be uniform with other files also. Previous comment message you used in ex1.py makes more sense, use it in every file since the structure of your code is almost same.

**Comment by jilesingh** [comment]
New changed have been made. Please check give me feedback regarding documentation.

**Comment by ABresting** [comment]
good.
