### ISSUE TITLE
Comment spacing.

### ISSUE THREAD

**Issue by ABresting** [jilesingh/LearnPythonTheHardWay#9]
https://github.com/jilesingh/LearnPythonTheHardWay/blob/cc6b6249d23658a044823926824596907735e2af/chapter1/ex40.py#L35

Before starting the commenting ther should be a space between # and <comment>

**Comment by jilesingh** [comment]
I have made some changes could you please check and give me feedback.
Thanks

**Comment by ABresting** [comment]
all wrong, read my comment again, one space between # and comment, not at the beginning of the line
